sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t richcastro82/dca-node-app -f Dockerfile.dev .

script:
  - docker run -e CI=true richcastro82/dca-node-app npm run test
